"use client";

import { useId } from "react";

type Country = { code: string; dial: string; flag: string; label: string };

const COUNTRIES: Country[] = [
  { code: "TR", dial: "+90", flag: "🇹🇷", label: "Türkiye" },
  { code: "US", dial: "+1", flag: "🇺🇸", label: "United States" },
  { code: "GB", dial: "+44", flag: "🇬🇧", label: "United Kingdom" },
  { code: "DE", dial: "+49", flag: "🇩🇪", label: "Germany" },
  { code: "FR", dial: "+33", flag: "🇫🇷", label: "France" },
  { code: "NL", dial: "+31", flag: "🇳🇱", label: "Netherlands" },
  { code: "AF", dial: "+93", flag: "🇦🇫", label: "Afghanistan" },
  { code: "AL", dial: "+355", flag: "🇦🇱", label: "Albania" },
  { code: "DZ", dial: "+213", flag: "🇩🇿", label: "Algeria" },
  { code: "AD", dial: "+376", flag: "🇦🇩", label: "Andorra" },
  { code: "AO", dial: "+244", flag: "🇦🇴", label: "Angola" },
  { code: "AR", dial: "+54", flag: "🇦🇷", label: "Argentina" },
  { code: "AM", dial: "+374", flag: "🇦🇲", label: "Armenia" },
  { code: "AU", dial: "+61", flag: "🇦🇺", label: "Australia" },
  { code: "AT", dial: "+43", flag: "🇦🇹", label: "Austria" },
  { code: "AZ", dial: "+994", flag: "🇦🇿", label: "Azerbaijan" },
  { code: "BS", dial: "+1", flag: "🇧🇸", label: "Bahamas" },
  { code: "BH", dial: "+973", flag: "🇧🇭", label: "Bahrain" },
  { code: "BD", dial: "+880", flag: "🇧🇩", label: "Bangladesh" },
  { code: "BB", dial: "+1", flag: "🇧🇧", label: "Barbados" },
  { code: "BY", dial: "+375", flag: "🇧🇾", label: "Belarus" },
  { code: "BE", dial: "+32", flag: "🇧🇪", label: "Belgium" },
  { code: "BZ", dial: "+501", flag: "🇧🇿", label: "Belize" },
  { code: "BJ", dial: "+229", flag: "🇧🇯", label: "Benin" },
  { code: "BT", dial: "+975", flag: "🇧🇹", label: "Bhutan" },
  { code: "BO", dial: "+591", flag: "🇧🇴", label: "Bolivia" },
  { code: "BA", dial: "+387", flag: "🇧🇦", label: "Bosnia & Herzegovina" },
  { code: "BW", dial: "+267", flag: "🇧🇼", label: "Botswana" },
  { code: "BR", dial: "+55", flag: "🇧🇷", label: "Brazil" },
  { code: "BN", dial: "+673", flag: "🇧🇳", label: "Brunei" },
  { code: "BG", dial: "+359", flag: "🇧🇬", label: "Bulgaria" },
  { code: "BF", dial: "+226", flag: "🇧🇫", label: "Burkina Faso" },
  { code: "BI", dial: "+257", flag: "🇧🇮", label: "Burundi" },
  { code: "KH", dial: "+855", flag: "🇰🇭", label: "Cambodia" },
  { code: "CM", dial: "+237", flag: "🇨🇲", label: "Cameroon" },
  { code: "CA", dial: "+1", flag: "🇨🇦", label: "Canada" },
  { code: "CF", dial: "+236", flag: "🇨🇫", label: "Central African Republic" },
  { code: "TD", dial: "+235", flag: "🇹🇩", label: "Chad" },
  { code: "CL", dial: "+56", flag: "🇨🇱", label: "Chile" },
  { code: "CN", dial: "+86", flag: "🇨🇳", label: "China" },
  { code: "CO", dial: "+57", flag: "🇨🇴", label: "Colombia" },
  { code: "KM", dial: "+269", flag: "🇰🇲", label: "Comoros" },
  { code: "CD", dial: "+243", flag: "🇨🇩", label: "Congo, Dem. Rep." },
  { code: "CG", dial: "+242", flag: "🇨🇬", label: "Congo, Republic" },
  { code: "CR", dial: "+506", flag: "🇨🇷", label: "Costa Rica" },
  { code: "HR", dial: "+385", flag: "🇭🇷", label: "Croatia" },
  { code: "CU", dial: "+53", flag: "🇨🇺", label: "Cuba" },
  { code: "CY", dial: "+357", flag: "🇨🇾", label: "Cyprus" },
  { code: "CZ", dial: "+420", flag: "🇨🇿", label: "Czech Republic" },
  { code: "DK", dial: "+45", flag: "🇩🇰", label: "Denmark" },
  { code: "DJ", dial: "+253", flag: "🇩🇯", label: "Djibouti" },
  { code: "DM", dial: "+1", flag: "🇩🇲", label: "Dominica" },
  { code: "DO", dial: "+1", flag: "🇩🇴", label: "Dominican Republic" },
  { code: "EC", dial: "+593", flag: "🇪🇨", label: "Ecuador" },
  { code: "EG", dial: "+20", flag: "🇪🇬", label: "Egypt" },
  { code: "SV", dial: "+503", flag: "🇸🇻", label: "El Salvador" },
  { code: "GQ", dial: "+240", flag: "🇬🇶", label: "Equatorial Guinea" },
  { code: "ER", dial: "+291", flag: "🇪🇷", label: "Eritrea" },
  { code: "EE", dial: "+372", flag: "🇪🇪", label: "Estonia" },
  { code: "SZ", dial: "+268", flag: "🇸🇿", label: "Eswatini" },
  { code: "ET", dial: "+251", flag: "🇪🇹", label: "Ethiopia" },
  { code: "FJ", dial: "+679", flag: "🇫🇯", label: "Fiji" },
  { code: "FI", dial: "+358", flag: "🇫🇮", label: "Finland" },
  { code: "GA", dial: "+241", flag: "🇬🇦", label: "Gabon" },
  { code: "GM", dial: "+220", flag: "🇬🇲", label: "Gambia" },
  { code: "GE", dial: "+995", flag: "🇬🇪", label: "Georgia" },
  { code: "GH", dial: "+233", flag: "🇬🇭", label: "Ghana" },
  { code: "GR", dial: "+30", flag: "🇬🇷", label: "Greece" },
  { code: "GD", dial: "+1", flag: "🇬🇩", label: "Grenada" },
  { code: "GT", dial: "+502", flag: "🇬🇹", label: "Guatemala" },
  { code: "GN", dial: "+224", flag: "🇬🇳", label: "Guinea" },
  { code: "GW", dial: "+245", flag: "🇬🇼", label: "Guinea-Bissau" },
  { code: "GY", dial: "+592", flag: "🇬🇾", label: "Guyana" },
  { code: "HT", dial: "+509", flag: "🇭🇹", label: "Haiti" },
  { code: "HN", dial: "+504", flag: "🇭🇳", label: "Honduras" },
  { code: "HU", dial: "+36", flag: "🇭🇺", label: "Hungary" },
  { code: "IS", dial: "+354", flag: "🇮🇸", label: "Iceland" },
  { code: "IN", dial: "+91", flag: "🇮🇳", label: "India" },
  { code: "ID", dial: "+62", flag: "🇮🇩", label: "Indonesia" },
  { code: "IR", dial: "+98", flag: "🇮🇷", label: "Iran" },
  { code: "IQ", dial: "+964", flag: "🇮🇶", label: "Iraq" },
  { code: "IE", dial: "+353", flag: "🇮🇪", label: "Ireland" },
  { code: "IL", dial: "+972", flag: "🇮🇱", label: "Israel" },
  { code: "IT", dial: "+39", flag: "🇮🇹", label: "Italy" },
  { code: "JM", dial: "+1", flag: "🇯🇲", label: "Jamaica" },
  { code: "JP", dial: "+81", flag: "🇯🇵", label: "Japan" },
  { code: "JO", dial: "+962", flag: "🇯🇴", label: "Jordan" },
  { code: "KZ", dial: "+7", flag: "🇰🇿", label: "Kazakhstan" },
  { code: "KE", dial: "+254", flag: "🇰🇪", label: "Kenya" },
  { code: "KI", dial: "+686", flag: "🇰🇮", label: "Kiribati" },
  { code: "KP", dial: "+850", flag: "🇰🇵", label: "Korea, North" },
  { code: "KR", dial: "+82", flag: "🇰🇷", label: "Korea, South" },
  { code: "KW", dial: "+965", flag: "🇰🇼", label: "Kuwait" },
  { code: "KG", dial: "+996", flag: "🇰🇬", label: "Kyrgyzstan" },
  { code: "LA", dial: "+856", flag: "🇱🇦", label: "Laos" },
  { code: "LV", dial: "+371", flag: "🇱🇻", label: "Latvia" },
  { code: "LB", dial: "+961", flag: "🇱🇧", label: "Lebanon" },
  { code: "LS", dial: "+266", flag: "🇱🇸", label: "Lesotho" },
  { code: "LR", dial: "+231", flag: "🇱🇷", label: "Liberia" },
  { code: "LY", dial: "+218", flag: "🇱🇾", label: "Libya" },
  { code: "LI", dial: "+423", flag: "🇱🇮", label: "Liechtenstein" },
  { code: "LT", dial: "+370", flag: "🇱🇹", label: "Lithuania" },
  { code: "LU", dial: "+352", flag: "🇱🇺", label: "Luxembourg" },
  { code: "MG", dial: "+261", flag: "🇲🇬", label: "Madagascar" },
  { code: "MW", dial: "+265", flag: "🇲🇼", label: "Malawi" },
  { code: "MY", dial: "+60", flag: "🇲🇾", label: "Malaysia" },
  { code: "MV", dial: "+960", flag: "🇲🇻", label: "Maldives" },
  { code: "ML", dial: "+223", flag: "🇲🇱", label: "Mali" },
  { code: "MT", dial: "+356", flag: "🇲🇹", label: "Malta" },
  { code: "MH", dial: "+692", flag: "🇲🇭", label: "Marshall Islands" },
  { code: "MR", dial: "+222", flag: "🇲🇷", label: "Mauritania" },
  { code: "MU", dial: "+230", flag: "🇲🇺", label: "Mauritius" },
  { code: "MX", dial: "+52", flag: "🇲🇽", label: "Mexico" },
  { code: "FM", dial: "+691", flag: "🇫🇲", label: "Micronesia" },
  { code: "MD", dial: "+373", flag: "🇲🇩", label: "Moldova" },
  { code: "MC", dial: "+377", flag: "🇲🇨", label: "Monaco" },
  { code: "MN", dial: "+976", flag: "🇲🇳", label: "Mongolia" },
  { code: "ME", dial: "+382", flag: "🇲🇪", label: "Montenegro" },
  { code: "MA", dial: "+212", flag: "🇲🇦", label: "Morocco" },
  { code: "MZ", dial: "+258", flag: "🇲🇿", label: "Mozambique" },
  { code: "MM", dial: "+95", flag: "🇲🇲", label: "Myanmar" },
  { code: "NA", dial: "+264", flag: "🇳🇦", label: "Namibia" },
  { code: "NR", dial: "+674", flag: "🇳🇷", label: "Nauru" },
  { code: "NP", dial: "+977", flag: "🇳🇵", label: "Nepal" },
  { code: "NZ", dial: "+64", flag: "🇳🇿", label: "New Zealand" },
  { code: "NI", dial: "+505", flag: "🇳🇮", label: "Nicaragua" },
  { code: "NE", dial: "+227", flag: "🇳🇪", label: "Niger" },
  { code: "NG", dial: "+234", flag: "🇳🇬", label: "Nigeria" },
  { code: "MK", dial: "+389", flag: "🇲🇰", label: "North Macedonia" },
  { code: "NO", dial: "+47", flag: "🇳🇴", label: "Norway" },
  { code: "OM", dial: "+968", flag: "🇴🇲", label: "Oman" },
  { code: "PK", dial: "+92", flag: "🇵🇰", label: "Pakistan" },
  { code: "PW", dial: "+680", flag: "🇵🇼", label: "Palau" },
  { code: "PS", dial: "+970", flag: "🇵🇸", label: "Palestine" },
  { code: "PA", dial: "+507", flag: "🇵🇦", label: "Panama" },
  { code: "PG", dial: "+675", flag: "🇵🇬", label: "Papua New Guinea" },
  { code: "PY", dial: "+595", flag: "🇵🇾", label: "Paraguay" },
  { code: "PE", dial: "+51", flag: "🇵🇪", label: "Peru" },
  { code: "PH", dial: "+63", flag: "🇵🇭", label: "Philippines" },
  { code: "PL", dial: "+48", flag: "🇵🇱", label: "Poland" },
  { code: "PT", dial: "+351", flag: "🇵🇹", label: "Portugal" },
  { code: "QA", dial: "+974", flag: "🇶🇦", label: "Qatar" },
  { code: "RO", dial: "+40", flag: "🇷🇴", label: "Romania" },
  { code: "RU", dial: "+7", flag: "🇷🇺", label: "Russia" },
  { code: "RW", dial: "+250", flag: "🇷🇼", label: "Rwanda" },
  { code: "KN", dial: "+1", flag: "🇰🇳", label: "St. Kitts & Nevis" },
  { code: "LC", dial: "+1", flag: "🇱🇨", label: "St. Lucia" },
  { code: "VC", dial: "+1", flag: "🇻🇨", label: "St. Vincent & Grenadines" },
  { code: "WS", dial: "+685", flag: "🇼🇸", label: "Samoa" },
  { code: "SM", dial: "+378", flag: "🇸🇲", label: "San Marino" },
  { code: "ST", dial: "+239", flag: "🇸🇹", label: "Sao Tome & Principe" },
  { code: "SA", dial: "+966", flag: "🇸🇦", label: "Saudi Arabia" },
  { code: "SN", dial: "+221", flag: "🇸🇳", label: "Senegal" },
  { code: "RS", dial: "+381", flag: "🇷🇸", label: "Serbia" },
  { code: "SC", dial: "+248", flag: "🇸🇨", label: "Seychelles" },
  { code: "SL", dial: "+232", flag: "🇸🇱", label: "Sierra Leone" },
  { code: "SG", dial: "+65", flag: "🇸🇬", label: "Singapore" },
  { code: "SK", dial: "+421", flag: "🇸🇰", label: "Slovakia" },
  { code: "SI", dial: "+386", flag: "🇸🇮", label: "Slovenia" },
  { code: "SB", dial: "+677", flag: "🇸🇧", label: "Solomon Islands" },
  { code: "SO", dial: "+252", flag: "🇸🇴", label: "Somalia" },
  { code: "ZA", dial: "+27", flag: "🇿🇦", label: "South Africa" },
  { code: "SS", dial: "+211", flag: "🇸🇸", label: "South Sudan" },
  { code: "ES", dial: "+34", flag: "🇪🇸", label: "Spain" },
  { code: "LK", dial: "+94", flag: "🇱🇰", label: "Sri Lanka" },
  { code: "SD", dial: "+249", flag: "🇸🇩", label: "Sudan" },
  { code: "SR", dial: "+597", flag: "🇸🇷", label: "Suriname" },
  { code: "SE", dial: "+46", flag: "🇸🇪", label: "Sweden" },
  { code: "CH", dial: "+41", flag: "🇨🇭", label: "Switzerland" },
  { code: "SY", dial: "+963", flag: "🇸🇾", label: "Syria" },
  { code: "TW", dial: "+886", flag: "🇹🇼", label: "Taiwan" },
  { code: "TJ", dial: "+992", flag: "🇹🇯", label: "Tajikistan" },
  { code: "TZ", dial: "+255", flag: "🇹🇿", label: "Tanzania" },
  { code: "TH", dial: "+66", flag: "🇹🇭", label: "Thailand" },
  { code: "TL", dial: "+670", flag: "🇹🇱", label: "Timor-Leste" },
  { code: "TG", dial: "+228", flag: "🇹🇬", label: "Togo" },
  { code: "TO", dial: "+676", flag: "🇹🇴", label: "Tonga" },
  { code: "TT", dial: "+1", flag: "🇹🇹", label: "Trinidad & Tobago" },
  { code: "TN", dial: "+216", flag: "🇹🇳", label: "Tunisia" },
  { code: "TM", dial: "+993", flag: "🇹🇲", label: "Turkmenistan" },
  { code: "TV", dial: "+688", flag: "🇹🇻", label: "Tuvalu" },
  { code: "UG", dial: "+256", flag: "🇺🇬", label: "Uganda" },
  { code: "UA", dial: "+380", flag: "🇺🇦", label: "Ukraine" },
  { code: "AE", dial: "+971", flag: "🇦🇪", label: "United Arab Emirates" },
  { code: "UY", dial: "+598", flag: "🇺🇾", label: "Uruguay" },
  { code: "UZ", dial: "+998", flag: "🇺🇿", label: "Uzbekistan" },
  { code: "VU", dial: "+678", flag: "🇻🇺", label: "Vanuatu" },
  { code: "VA", dial: "+379", flag: "🇻🇦", label: "Vatican City" },
  { code: "VE", dial: "+58", flag: "🇻🇪", label: "Venezuela" },
  { code: "VN", dial: "+84", flag: "🇻🇳", label: "Vietnam" },
  { code: "YE", dial: "+967", flag: "🇾🇪", label: "Yemen" },
  { code: "ZM", dial: "+260", flag: "🇿🇲", label: "Zambia" },
  { code: "ZW", dial: "+263", flag: "🇿🇼", label: "Zimbabwe" },
];

export default function PhoneField() {
  const selectId = useId();
  const inputId = useId();

  return (
    <div className="flex gap-2">
      <div className="relative">
        <label htmlFor={selectId} className="sr-only">Country code</label>
        <select
          id={selectId}
          name="phone_country"
          className="input pr-8 w-40"
          defaultValue="TR"
        >
          {COUNTRIES.map(c => (
            <option key={c.code} value={c.code}>
              {c.flag} {c.label} ({c.dial})
            </option>
          ))}
        </select>
        {/* sağ oka ekstra boşluk vermek için pr-8 kullandık */}
      </div>

      <div className="flex-1">
        <label htmlFor={inputId} className="sr-only">Phone number</label>
        <input
          id={inputId}
          name="phone_local"
          type="tel"
          inputMode="tel"
          placeholder="5xx xxx xx xx"
          className="input"
          autoComplete="tel-national"
        />
      </div>
    </div>
  );
}